name: Publish shiny rates

on:
  schedule:
    # these are 12AM, 6AM, 12PM, 6PM Central
    - cron: '0 5,11,17,23 * * *'
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    # Check out code
    - uses: actions/checkout@v2

    # Run Python stuff
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas
    - name: Run Python scraper
      run: python main.py

    - name: Publish back to master
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
